# Batch 3 - 30 Files
$files = @(
    "api/shared/db.js",
    "api/shared/firebase-admin.js",
    "api/shared/encryptionUtils.js",
    "api/shared/encryptedQueries.js",
    "api/shared/auditLog.js",
    "api/shared/sessionManager.js",
    "api/services/authService.js",
    "api/services/twoFAService.js",
    "api/services/stripeService.js",
    "api/routes/auth-endpoints/register.js",
    "api/routes/auth-endpoints/account.js",
    "api/routes/auth-endpoints/2fa.js",
    "api/routes/auth-endpoints/account-reactivation.js",
    "api/routes/auth-endpoints/preferences.js",
    "api/routes/astrology.js",
    "api/routes/horoscope.js",
    "api/routes/moon-phase.js",
    "api/routes/astrology-insights.js",
    "api/routes/chat.js",
    "api/routes/migration.js",
    "api/middleware/auth.js",
    "api/middleware/inputValidation.js",
    "api/middleware/rateLimiter.js",
    "api/middleware/consentCheck.js",
    "api/shared/smsService.js",
    "api/shared/emailService.js",
    "api/shared/queue.js",
    "api/routes/user-profile.js",
    "api/routes/user-settings.js",
    "api/routes/billing/subscriptions.js"
)

& .\BULK_CONSOLE_FIX_V4.ps1 -BatchName "Batch-3-30Files" -Files $files
