# Batch CLIENT_2: Files 31-60 of 90
$Files = @(
    "client/src/context/TranslationContext.jsx",
    "client/src/context/TranslationContext-DEEPMERGE.jsx",
    "client/src/data/zodiac/index.js",
    "client/src/hooks/auth/useAuthBilling.js",
    "client/src/hooks/auth/useAuthSession.js",
    "client/src/hooks/auth/useAuthState.js",
    "client/src/hooks/auth/useAuthTwoFactor.js",
    "client/src/hooks/billing/billingApi.js",
    "client/src/hooks/billing/usePaymentMethods.js",
    "client/src/hooks/useAstroData.js",
    "client/src/hooks/useAstroInfo.js",
    "client/src/hooks/useAstrologyPolling.js",
    "client/src/hooks/useAuthAPI.js",
    "client/src/hooks/useAuthHandlers.js",
    "client/src/hooks/useChatMigration.js",
    "client/src/hooks/useCosmicWeatherData.js",
    "client/src/hooks/useDeviceLocation.js",
    "client/src/hooks/useEmailVerification.js",
    "client/src/hooks/useHashedUserId.js",
    "client/src/hooks/useHoroscopeData.js",
    "client/src/hooks/useHoroscopeFetch.js",
    "client/src/hooks/useHoroscopePolling.js",
    "client/src/hooks/useHoroscopePreferences.js",
    "client/src/hooks/useLanguagePreference.js",
    "client/src/hooks/useMoonPhaseData.js",
    "client/src/hooks/useOnboarding.js",
    "client/src/hooks/usePersonalInfo.js",
    "client/src/hooks/usePersonalInfoAPI.js",
    "client/src/hooks/useRegistrationFlow.js",
    "client/src/hooks/useSpeech.js"
)

& .\BULK_CONSOLE_FIX_V10_CORRECTED.ps1 -Files $Files -BatchName "CLIENT_BATCH_2"
