export const majorArcana = [
// MAJOR ARCANA (0-21)
    {
        id: 0, name: "The Fool", suit: "major", number: 0,
        keywords: ["new beginnings", "innocence", "spontaneity", "free spirit"],
        upright: "New beginnings, innocence, spontaneity, a free spirit. The Fool represents new adventures, having faith in the future, being inexperienced, not knowing what to expect. Trust in the universe and believe that everything will work out as it should.",
        reversed: "Holding back, recklessness, risk-taking. When reversed, The Fool suggests you are living life to the extreme, either being completely reckless or overly cautious. Take calculated risks and find balance.",
        element: "Air", astrology: "Uranus",
        hebrew_letter: "Aleph", hebrew_meaning: "Ox", hebrew_value: 1,
        meaning: "New beginnings, innocence, spontaneity, free spirit",
        color: "Pale yellow, bright pale yellow",
        musical_note: "E natural",
        herbs_oils: "Galbanum, peppermint, aspen"
    },
    {
        id: 1, name: "The Magician", suit: "major", number: 1,
        keywords: ["manifestation", "resourcefulness", "power", "inspired action"],
        upright: "Manifestation, resourcefulness, power, inspired action. The Magician represents having the skill, talent and capabilities to succeed. You have the tools and resources available to manifest your desires.",
        reversed: "Manipulation, poor planning, untapped talents. Reversed suggests you may be struggling to harness your inner power or using your abilities in manipulative ways. Focus your energy constructively.",
        element: "Air", astrology: "Mercury",
        hebrew_letter: "Beth", hebrew_meaning: "House", hebrew_value: 2,
        meaning: "Manifestation, resourcefulness, power, inspired action",
        color: "Yellow",
        musical_note: "E",
        herbs_oils: "Mastic, lavender, fennel, marjoram"
    },
    {
        id: 2, name: "The High Priestess", suit: "major", number: 2,
        keywords: ["intuition", "sacred knowledge", "divine feminine", "subconscious mind"],
        upright: "Intuition, sacred knowledge, divine feminine, the subconscious mind. Trust your intuition and go with your gut feeling. Look for the deeper meaning and listen to your inner voice.",
        reversed: "Secrets, disconnected from intuition, withdrawal. When reversed, you may be out of touch with your intuitive side or keeping secrets. Reconnect with your inner wisdom.",
        element: "Water", astrology: "Moon",
        hebrew_letter: "Gimel", hebrew_meaning: "Camel", hebrew_value: 3,
        meaning: "Intuition, sacred knowledge, divine feminine, the subconscious",
        color: "Blue, silver",
        musical_note: "G#",
        herbs_oils: "Camphor, almond, jasmine, myrrh"
    },
    {
        id: 3, name: "The Empress", suit: "major", number: 3,
        keywords: ["femininity", "beauty", "nature", "nurturing", "abundance"],
        upright: "Femininity, beauty, nature, nurturing, abundance. The Empress represents the creation of life, romance, art, or business. She suggests fertility, creative expression, and abundance in all forms.",
        reversed: "Creative block, dependence on others, smothering. Reversed may indicate creative blocks, lack of growth, or being overly dependent on others. Focus on self-care and independence.",
        element: "Earth", astrology: "Venus",
        hebrew_letter: "Daleth", hebrew_meaning: "Door", hebrew_value: 4,
        meaning: "Femininity, beauty, nature, nurturing, abundance",
        color: "Emerald green",
        musical_note: "F#",
        herbs_oils: "Rose, myrtle, sandalwood, benzoin"
    },
    {
        id: 4, name: "The Emperor", suit: "major", number: 4,
        keywords: ["authority", "establishment", "structure", "fatherly figure"],
        upright: "Authority, establishment, structure, fatherly figure. The Emperor represents authority, structure, control, and fatherly love. Create law and order through discipline and routine.",
        reversed: "Domination, excessive control, lack of discipline. When reversed, The Emperor suggests too much control, being overly rigid, or lack of authority. Find balance between control and flexibility.",
        element: "Fire", astrology: "Aries",
        hebrew_letter: "Heh", hebrew_meaning: "Window", hebrew_value: 5,
        meaning: "Authority, establishment, structure, father figure",
        color: "Scarlet red",
        musical_note: "C",
        herbs_oils: "Dragon's blood, ginger, pepper, tobacco"
    },
    {
        id: 5, name: "The Hierophant", suit: "major", number: 5,
        keywords: ["spiritual wisdom", "religious beliefs", "conformity", "tradition"],
        upright: "Spiritual wisdom, religious beliefs, conformity, tradition, institutions. Seek guidance from a mentor or spiritual advisor. Follow established traditions and conventional methods.",
        reversed: "Personal beliefs, freedom, challenging tradition. Reversed suggests breaking away from tradition, creating your own path, and following personal beliefs rather than established doctrine.",
        element: "Earth", astrology: "Taurus",
        hebrew_letter: "Vav", hebrew_meaning: "Nail/Hook", hebrew_value: 6,
        meaning: "Spiritual wisdom, religious beliefs, conformity, tradition",
        color: "Red-orange",
        musical_note: "C#",
        herbs_oils: "Storax, mallow, verbena"
    },
    {
        id: 6, name: "The Lovers", suit: "major", number: 6,
        keywords: ["love", "harmony", "relationships", "values alignment"],
        upright: "Love, harmony, relationships, values alignment. Perfect union, harmony, love, and attraction. Important decisions about relationships, values, and personal beliefs.",
        reversed: "Self-love, disharmony, imbalance, misalignment. When reversed, focus on self-love first, or indicates relationship troubles and conflicts in values.",
        element: "Air", astrology: "Gemini",
        hebrew_letter: "Zayin", hebrew_meaning: "Sword/Weapon", hebrew_value: 7,
        meaning: "Love, harmony, relationships, choices, alignment",
        color: "Orange",
        musical_note: "D",
        herbs_oils: "Wormwood, lavender, peppermint, bergamot"
    },
    {
        id: 7, name: "The Chariot", suit: "major", number: 7,
        keywords: ["control", "willpower", "success", "determination"],
        upright: "Control, willpower, success, determination. Maintain focus and determination to overcome challenges. Victory through maintaining control of opposing forces.",
        reversed: "Lack of control, lack of direction, aggression. Reversed suggests losing control, lack of direction, or aggressive behavior. Regain focus and find your path forward.",
        element: "Water", astrology: "Cancer",
        hebrew_letter: "Cheth", hebrew_meaning: "Fence/Enclosure", hebrew_value: 8,
        meaning: "Control, willpower, success, determination",
        color: "Amber/Orange-yellow",
        musical_note: "D#",
        herbs_oils: "Lotus, onycha, camphor"
    },
    {
        id: 8, name: "The Strength", suit: "major", number: 8,
        keywords: ["strength", "courage", "persuasion", "influence", "compassion"],
        upright: "Strength, courage, persuasion, influence, compassion. Inner strength, bravery, compassion, and focus. Gentle control and overcoming challenges through love rather than force.",
        reversed: "Self doubt, lack of confidence, lack of self-discipline. When reversed, indicates inner turmoil, self-doubt, or lack of confidence. Build inner strength and self-compassion.",
        element: "Fire", astrology: "Leo",
        hebrew_letter: "Teth", hebrew_meaning: "Serpent", hebrew_value: 9,
        meaning: "Strength, courage, patience, compassion, inner power",
        color: "Yellow-green, greenish-yellow",
        musical_note: "E",
        herbs_oils: "Olibanum (frankincense), cinnamon, sunflower"
    },
    {
        id: 9, name: "The Hermit", suit: "major", number: 9,
        keywords: ["soul searching", "introspection", "inner guidance"],
        upright: "Soul searching, introspection, inner guidance. Seek inner guidance and solitude for personal growth. Take time for self-reflection and spiritual enlightenment.",
        reversed: "Isolation, loneliness, withdrawal. Reversed suggests excessive isolation or withdrawal from others. Balance solitude with social connection.",
        element: "Earth", astrology: "Virgo",
        hebrew_letter: "Yod", hebrew_meaning: "Hand", hebrew_value: 10,
        meaning: "Soul-searching, introspection, inner guidance, solitude",
        color: "Yellow-green, greenish yellow",
        musical_note: "F",
        herbs_oils: "Snowdrop, lily, narcissus, sage"
    },
    {
        id: 10, name: "The Wheel of Fortune", suit: "major", number: 10,
        keywords: ["good luck", "karma", "life cycles", "destiny", "turning point"],
        upright: "Good luck, karma, life cycles, destiny, turning point. Positive change, good fortune, and karmic rewards. Life is cyclical - what goes around comes around.",
        reversed: "Bad luck, lack of control, clinging to control. When reversed, indicates temporary setbacks or feeling like you have no control. Trust that this phase will pass.",
        element: "Fire", astrology: "Jupiter",
        hebrew_letter: "Kaph", hebrew_meaning: "Palm of hand", hebrew_value: 20,
        meaning: "Good luck, karma, life cycles, destiny, turning point",
        color: "Violet, rich purple",
        musical_note: "A#",
        herbs_oils: "Hyssop, oak, cedar, nutmeg"
    },
    {
        id: 11, name: "The Justice", suit: "major", number: 11,
        keywords: ["justice", "fairness", "truth", "cause and effect", "law"],
        upright: "Justice, fairness, truth, cause and effect, law. Seek truth and fairness. Legal matters may be resolved in your favor. Take responsibility for your actions.",
        reversed: "Unfairness, lack of accountability, dishonesty. Reversed suggests injustice, corruption, or avoiding responsibility. Strive for fairness and honesty.",
        element: "Air", astrology: "Libra",
        hebrew_letter: "Lamed", hebrew_meaning: "Ox goad", hebrew_value: 30,
        meaning: "Justice, fairness, truth, cause and effect, law",
        color: "Emerald green",
        musical_note: "F#",
        herbs_oils: "Galbanum, rose, aloe"
    },
    {
        id: 12, name: "The Hanged Man", suit: "major", number: 12,
        keywords: ["suspension", "restriction", "letting go", "sacrifice"],
        upright: "Suspension, restriction, letting go, sacrifice. Sometimes you need to suspend action and wait. Let go of control and see things from a new perspective.",
        reversed: "Delays, resistance, stalling. When reversed, indicates unnecessary delays or resistance to necessary change. Stop fighting and allow natural flow.",
        element: "Water", astrology: "Neptune",
        hebrew_letter: "Mem", hebrew_meaning: "Water", hebrew_value: 40,
        meaning: "Suspension, restriction, letting go, new perspective",
        color: "Deep blue, sea blue",
        musical_note: "G#",
        herbs_oils: "Myrrh, lotus, kelp"
    },
    {
        id: 13, name: "Death", suit: "major", number: 13,
        keywords: ["endings", "change", "transformation", "transition"],
        upright: "Endings, change, transformation, transition. Major transformation and new beginnings. Release the old to make way for the new. Embrace change.",
        reversed: "Resistance to change, personal transformation, inner purging. Reversed suggests resisting necessary change or going through inner transformation. Embrace the process.",
        element: "Water", astrology: "Scorpio",
        hebrew_letter: "Nun", hebrew_meaning: "Fish", hebrew_value: 50,
        meaning: "Endings, change, transformation, transition",
        color: "Blue-green",
        musical_note: "G",
        herbs_oils: "Opoponax, benzoin, patchouli"
    },
    {
        id: 14, name: "Temperance", suit: "major", number: 14,
        keywords: ["balance", "moderation", "patience", "purpose"],
        upright: "Balance, moderation, patience, purpose. Find balance and avoid extremes. Patience and moderation will bring about harmony. Blend opposing forces.",
        reversed: "Imbalance, excess, self-healing, re-alignment. When reversed, suggests imbalance or excess. Take time to realign and find your center.",
        element: "Fire", astrology: "Sagittarius",
        hebrew_letter: "Samech", hebrew_meaning: "Prop/Support", hebrew_value: 60,
        meaning: "Balance, moderation, patience, purpose, meaning",
        color: "Blue",
        musical_note: "G#",
        herbs_oils: "Rush, aloe, lign aloes"
    },
    {
        id: 15, name: "The Devil", suit: "major", number: 15,
        keywords: ["shadow self", "attachment", "addiction", "restriction", "sexuality"],
        upright: "Shadow self, attachment, addiction, restriction, sexuality. Feeling trapped by material desires or unhealthy habits. Acknowledge your shadow self and break free from bondage.",
        reversed: "Releasing limiting beliefs, exploring dark thoughts, detachment. Reversed suggests breaking free from restrictions and releasing limiting beliefs. Embrace your authentic self.",
        element: "Earth", astrology: "Capricorn",
        hebrew_letter: "Ayin", hebrew_meaning: "Eye", hebrew_value: 70,
        meaning: "Shadow self, attachment, addiction, restriction, materialism",
        color: "Indigo, blue-violet",
        musical_note: "A",
        herbs_oils: "Musk, civet, patchouli, black pepper"
    },
    {
        id: 16, name: "The Tower", suit: "major", number: 16,
        keywords: ["sudden change", "upheaval", "chaos", "revelation", "awakening"],
        upright: "Sudden change, upheaval, chaos, revelation, awakening. Dramatic upheaval and sudden change. Destruction of false beliefs and structures. Spiritual awakening through crisis.",
        reversed: "Personal transformation, fear of change, averting disaster. When reversed, suggests avoiding disaster or going through personal transformation. Change is coming whether you resist or not.",
        element: "Fire", astrology: "Mars",
        hebrew_letter: "Peh", hebrew_meaning: "Mouth", hebrew_value: 80,
        meaning: "Sudden change, upheaval, chaos, revelation, awakening",
        color: "Scarlet",
        musical_note: "C",
        herbs_oils: "Pepper, tobacco, nettle, dragon's blood"
    },
    {
        id: 17, name: "The Star", suit: "major", number: 17,
        keywords: ["hope", "faith", "purpose", "renewal", "spirituality"],
        upright: "Hope, faith, purpose, renewal, spirituality. Renewed hope and faith after hardship. Spiritual guidance and inspiration. Follow your highest purpose.",
        reversed: "Lack of faith, despair, self-trust, disconnection. Reversed suggests losing faith or feeling disconnected from purpose. Reconnect with your inner guidance.",
        element: "Air", astrology: "Aquarius",
        hebrew_letter: "Tzaddi", hebrew_meaning: "Fishhook", hebrew_value: 90,
        meaning: "Hope, faith, purpose, renewal, spirituality",
        color: "Violet",
        musical_note: "A#",
        herbs_oils: "Olive, coconut, galbanum"
    },
    {
        id: 18, name: "The Moon", suit: "major", number: 18,
        keywords: ["illusion", "fear", "anxiety", "subconscious", "intuition"],
        upright: "Illusion, fear, anxiety, subconscious, intuition. Things are not as they seem. Trust your intuition but be aware of illusions and deception. Face your fears.",
        reversed: "Release of fear, repressed emotion, inner confusion. When reversed, suggests releasing fears and confusion. Listen to your inner voice and trust your intuition.",
        element: "Water", astrology: "Pisces",
        hebrew_letter: "Qoph", hebrew_meaning: "Back of head", hebrew_value: 100,
        meaning: "Illusion, fear, anxiety, subconscious, intuition",
        color: "Crimson (red tinged with purple)",
        musical_note: "B",
        herbs_oils: "Onycha, jasmine, opium poppy"
    },
    {
        id: 19, name: "The Sun", suit: "major", number: 19,
        keywords: ["happiness", "success", "optimism", "vitality", "joy"],
        upright: "Happiness, success, optimism, vitality, joy. Positive energy, success, and happiness. Everything is going well. Share your joy with others.",
        reversed: "Inner child, feeling down, overly optimistic. Reversed suggests temporary setbacks or need to reconnect with your inner child. Stay optimistic.",
        element: "Fire", astrology: "Sun",
        hebrew_letter: "Resh", hebrew_meaning: "Head", hebrew_value: 200,
        meaning: "Positivity, fun, warmth, success, vitality",
        color: "Orange, gold",
        musical_note: "D",
        herbs_oils: "Olibanum, cinnamon, frankincense, heliotrope"
    },
    {
        id: 20, name: "Judgment", suit: "major", number: 20,
        keywords: ["judgement", "rebirth", "inner calling", "absolution"],
        upright: "Judgement, rebirth, inner calling, absolution. Spiritual awakening and rebirth. Answer your higher calling. Forgiveness and second chances.",
        reversed: "Self-doubt, inner critic, avoiding the call. When reversed, suggests self-doubt or avoiding your calling. Trust in your abilities and answer the call.",
        element: "Fire", astrology: "Pluto",
        hebrew_letter: "Shin", hebrew_meaning: "Tooth", hebrew_value: 300,
        meaning: "Judgement, rebirth, inner calling, absolution",
        color: "Red (glowing scarlet)",
        musical_note: "C",
        herbs_oils: "Olibanum, clove, cinnamon"
    },
    {
        id: 21, name: "The World", suit: "major", number: 21,
        keywords: ["completion", "accomplishment", "travel", "fulfillment"],
        upright: "Completion, accomplishment, travel, fulfillment. Achievement and completion of goals. Success and fulfillment. The end of a cycle and beginning of another.",
        reversed: "Seeking personal closure, short-cut to success, stagnation. Reversed suggests seeking closure or taking shortcuts. Complete what you started before moving on.",
        element: "Earth", astrology: "Saturn",
        hebrew_letter: "Tav", hebrew_meaning: "Cross/Mark", hebrew_value: 400,
        meaning: "Completion, accomplishment, travel, fulfillment",
        color: "Indigo, blue-violet, black",
        musical_note: "A",
        herbs_oils: "Cypress, opium, assafoetida, storax"
    }
];
