
FROM node:latest

ENV NODE_ENV=development
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV ASTROLOGY_LAMBDA_URL=${ASTROLOGY_LAMBDA_URL}

WORKDIR /app

# Copy and install Node dependencies
COPY package*.json ./
RUN npm install

COPY . .
CMD ["npm", "run", "dev"]
